"""
Django settings for ticketsolea project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
import environ
from pathlib import Path
from django.utils.translation import gettext_lazy as _


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(env_file=str(BASE_DIR / "ticketsolea" / ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#   SECRET_KEY = 'django-insecure-=gdpidf&l4a!nnyz7a#i+tqkgwqydu-ymir10-z!!pgg*t=5+@'
SECRET_KEY = env("SECRET_KEY")


# SECURITY WARNING: don't run with debug turned on in production!
#   DEBUG = True
DEBUG = env.bool('DEBUG', False)

#   ALLOWED_HOSTS = []
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')

# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'admin_custom',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ticketsolea.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ticketsolea.wsgi.application'

# CUSTOM DATABASE CONFIGURATION
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DATABASE_NAME'),
        'USER': env('DATABASE_USER'),
        'PASSWORD': env('DATABASE_PWD'),
        'HOST': env('DATABASE_HOST'),
        'PORT': env('DATABASE_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Provide a lists of languages which your site supports.
LANGUAGE = (
    ('fr', _('Français')),
    ('en', _('English')),
)

PAGE_LANGUAGES = "PAGE_LANGUAGES"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'website.User'

# LOGIN DEFAULT REDIRECT URL
LOGIN_REDIRECT_URL = '/'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# DJANGO JAZZMIN CONFIGURATION
JAZZMIN_SETTINGS = {
    "site_title": "",
    "site_header": "Tickets OLEA",
    "site_brand": "©",
    "site_logo": "admin_custom/img/logo.png",
    "site_logo_classes": "container",
    "custom_css": "admin_custom/css/custom.css",
    "order_with_respect_to": [
        'auth',
        'website',
    ],
    "related_modal_active": True,
    "navigation_expanded": True,
    "copyright": "TICKETS OLEA",
    "version": "1.0",
    "language_chooser": True,
    "PAGE_LANGUAGES": LANGUAGE,
    "custom_links": {
        "auth": [
            {
                "name": "Utilisateurs",
                "url": "admin:website_user_changelist",
                "icon": "fa fa-user",
                "permissions": ["auth.view_user"]
            }
        ],
        "website": [
            {
                "name": "Tableau de Bord",
                "url": "index",
                "icon": "fas fa-home",
            },
            {
                "name": "Tickets",
                "url": "tickets",
                "icon": "fas fa-ticket-alt",
                "permissions": ["website.can_view_tickets"]
            },
            {
                "name": "Types Tickets",
                "url": "types",
                "icon": "fa fa-credit-card",
                "permissions": ["website.can_view_types_tickets"]
            },
        ],
    },
    "hide_models": [
        'website.ticket',
        'website.typeticket',
        'website.user',
    ],
    "icons": {
        "auth": "fas fa-user-shield",
        "auth.Group": "fas fa-users",
        "website": "fas fa-box",
    },
    "change_view": {
        "auth": {
            "user": {
                "password": "Change Password",
            }
        }
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
}

# EMAIL SETTINGS
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = ''
EMAIL_PORT = 587
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_USE_TLS = True
EMAIL_HOST_NAME = 'Noreply TICKETS OLEA'