# Generated by Django 4.2.14 on 2024-07-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='website_users', to='auth.group', verbose_name='groups'),
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
    ]
