# Generated by Django 4.2.14 on 2024-09-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('can_view_ticket', 'Can view ticket'), ('can_edit_ticket', 'Can edit ticket'), ('can_delete_ticket', 'Can delete ticket')], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
