# Generated by Django 4.2.14 on 2024-08-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_user_groups_delete_authgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('can_view_tickets', 'Peut voir la liste des tickets')], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
