# Generated by Django 4.2.14 on 2024-08-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
