# Generated by Django 4.2.14 on 2024-09-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('can_view_tickets', 'Can view tickets')], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
