# Generated by Django 4.2.14 on 2024-09-17 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeticket',
            options={'permissions': [('can_view_typeticket', 'Can view type tickets')], 'verbose_name': 'Type de ticket', 'verbose_name_plural': 'Types de tickets'},
        ),
    ]
