# Generated by Django 4.2.14 on 2024-09-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_customuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DEVELOPPER', 'Developper'), ('CLIENT', 'Client'), ('DIRECTEUR', 'Directeur'), ('TESTEUR', 'Testeur')], default='ADMIN', max_length=50),
        ),
    ]
